### ISSUE TITLE
Updating server from build 230 to 231 causes crash

### ISSUE THREAD

**Issue by Devilin-Pixy** [RS485/LogisticsPipes#375]
When I update my server from build 230 to 231 it causes the server to crash. When I start a new single player world with the same client there is no crash however.
Here is the crash log from the server:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 08/06/14 15:39
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: logisticspipes/utils/gui/LogisticsBaseGuiScreen
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
    at java.lang.Class.getConstructors(Unknown Source)
    at logisticspipes.network.NewGuiHandler.intialize(NewGuiHandler.java:59)
    at logisticspipes.LogisticsPipes.<init>(LogisticsPipes.java:151)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:174)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:518)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:69)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.ClassNotFoundException: logisticspipes.utils.gui.LogisticsBaseGuiScreen
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
    ... 40 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.inventory.GuiContainer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows Server 2012 (amd64) version 6.2
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1301550480 bytes (1241 MB) / 1516765184 bytes (1446 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -XX:MaxPermSize=256M -Xmx4096M -Xms512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 66 mods loaded, 66 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{6.4.49.965} [Forge Mod Loader](forge.jar) Unloaded->Constructed
    Forge{9.11.1.965} [Minecraft Forge](forge.jar) Unloaded->Constructed
    Aroma1997Core{1.0.1.5} [Aroma1997Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.6.1.9} [Not Enough Items](NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](PowerCrystalsCore-1.1.8-9.jar) Unloaded->Constructed
    Aroma1997CoreHelper{1.0.1.5} [Aroma1997Core|Helper](Aroma1997Core MC.1.6.4 v.1.0.1.5.jar) Unloaded->Constructed
    AWWayofTime{v1.0.1} [Blood Magic: Alchemical Wizardry](Blood Magic v1.0.1b.zip) Unloaded->Constructed
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
    Additional-Buildcraft-Objects{1.0.7.561} [Additional Buildcraft Objects](buildcraft-Z-additional-buildcraft-objects-1.6.4-4.2.2-1.0.7.561.jar) Unloaded->Constructed
    IC2{2.0.397-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed
    CompactWindmills{1.0.3.0} [CompactWindmills](CompactWindmills MC.1.6.4 v.1.0.3.0.jar) Unloaded->Constructed
    ConfigMod{v1.0} [Extended Mod Config](ConfigMod for MC v1.6.4.zip) Unloaded->Constructed
    CoroAI{v1.0} [CoroAI](CoroUtil for MC v1.6.4.zip) Unloaded->Constructed
    dimdoors{1.6.4-R2.2.3} [Dimensional Doors](DimensionalDoors-2.2.3-326.jar) Unloaded->Constructed
    MineFactoryReloaded{1.6.4R2.7.9} [MineFactory Reloaded](MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForestryPre{1.6.4R2.7.9} [MFR Compat: Forestry (part 2)](MineFactoryReloaded-2.7.9-final.jar) Unloaded->Constructed
    Forestry{2.3.1.1} [Forestry for Minecraft](forestry-A-2.3.1.1.jar) Unloaded->Constructed
    GalacticraftCore{2.0.13} [Galacticraft Core](Galacticraft-1.6.4-2.0.13.1071.jar) Unloaded->Constructed
    GalacticraftMars{2.0.13} [Galacticraft Mars](Galacticraft-Planets-1.6.4-2.0.13.1071.jar) Unloaded->Constructed
    Railcraft{8.4.0.0} [Railcraft](Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed
    gregtech_addon{MC162} [GregTech-Addon](gregtechmod408s.zip) Unloaded->Constructed
    HardcoreEnderExpansion{1.6.1} [Hardcore Ender Expansion](HardcoreEnderExpansion.zip) Unloaded->Constructed
    HungerOverhaul{1.6.X-2l} [Hunger Overhaul](hungeroverhaul-1.6.X-2l-build3.zip) Unloaded->Constructed
    IC2Fixes{1.0} [IC2 Fixes](IC2FixesGT.jar) Unloaded->Constructed
    IC2NuclearControl{1.6.2e} [Nuclear Control](IC2NuclearControl-1.6.2e-ic2-experimental.zip) Unloaded->Constructed
    JABBA{1.1.3} [JABBA](JABBA_1.1.3.zip) Unloaded->Constructed
    Java7Checker{1.0} [Java 7 Checker](Java7Checker.zip) Unloaded->Constructed
    LogisticsPipes|Main{0.7.4.dev.231} [Logistics Pipes](LogisticsPipes-MC1.6.4-0.7.4.dev.231.jar) Unloaded
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.4R2.7.9} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatAtum{1.6.4R2.7.9} [MFR Compat: Atum](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatBackTools{1.6.4R2.7.9} [MFR Compat: BackTools](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatBuildCraft{1.6.4R2.7.9} [MFR Compat: BuildCraft](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatChococraft{1.6.4R2.7.9} [MFR Compat: Chococraft](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatExtraBiomes{1.6.4R2.7.9} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatForestry{1.6.4R2.7.9} [MFR Compat: Forestry](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatForgeMicroblock{1.6.4R2.7.9} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatIC2{1.6.4R2.7.9} [MFR Compat: IC2](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatMystcraft{1.6.4R2.7.9} [MFR Compat: Mystcraft](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatPams{1.6.4R2.7.9} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatProjRed{1.6.4R2.7.9} [MFR Compat ProjectRed](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatRailcraft{1.6.4R2.7.9} [MFR Compat: Railcraft](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatRP2{1.6.4R2.7.9} [MFR Compat: RP2](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatSufficientBiomes{1.6.4R2.7.9} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatThaumcraft{1.6.4R2.7.9} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatThermalExpansion{1.6.4R2.7.9} [MFR Compat: Thermal Expansion](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatTwilightForest{1.6.4R2.7.9} [MFR Compat: TwilightForest](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatVanilla{1.6.4R2.7.9} [MFR Compat: Vanilla](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    MineFactoryReloaded|CompatXyCraft{1.6.4R2.7.9} [MFR Compat: XyCraft](MineFactoryReloaded-2.7.9-final.jar) Unloaded
    AdvancedSolarPanel{3.4.7} [Advanced Solar Panels](mod_AdvancedSolarPanels_3_4_7_IC_EXP.zip) Unloaded
    Morpheus{1.2} [Morpheus](Morpheus-1.6.4-1.2.32.jar) Unloaded
    OpenComponents{0.1.0.29} [OpenComponents](OpenComponents-MC1.6.4-0.1.1.37-universal.jar) Unloaded
    UniversalElectricity{3.1.0} [Universal Electricity](Universal-Electricity-3.1.0.87-core.jar) Unloaded
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.6.4-1.2.12.376-universal.jar) Unloaded
    OpenComputers{1.2.12.376} [OpenComputers](OpenComputers-MC1.6.4-1.2.12.376-universal.jar) Unloaded
    UndergroundBiomes{0.4.3} [Underground Biomes](UndergroundBiomes 1.6.x - 0.4.2c.zip) Unloaded
    ZAMod{v1.91} [Zombie Awareness](Zombie Awareness v1.91 Mod for MC v1.6.4.zip) Unloaded
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by davboecki** [comment]
build 232 should fix that.
